using NewAvatarWebApis.Core.Application.DTOs;
using Newtonsoft.Json;

namespace NewAvatarWebApis.Core.Application.Responses
{
    public class ItemDetailsResponse
    {
        public string? ItemId { get; set; }
        public string? ItemSoliter { get; set; } 
        public string? ItemCtgCommonID { get; set; }
        public string? ItemAproxDay { get; set; }
        public string? ItemDAproxDay { get; set; } 
        public string? PlaingoldStatus { get; set; } 
        public string? ItemName { get; set; } 
        public string? ItemSku { get; set; } 
        public string? ItemDescription { get; set; } 
        public string? ItemMrp { get; set; }
        public string? ItemDiscount { get; set; }
        public string? ItemPrice { get; set; }
        public string? ItemBrandCommonID { get; set; }
        public string? ItemCd { get; set; }
        public string? RetailPrice { get; set; }
        public string? DistPrice { get; set; }
        public string? Uom { get; set; } 
        public string? Star { get; set; }
        public string? CartImg { get; set; } 
        public string? ImgCartTitle { get; set; } 
        public string? WatchImg { get; set; }
        public string? ImgWatchTitle { get; set; } 
        public string? WearitCount { get; set; }
        public string? WearitStatus { get; set; } 
        public string? WearitImg { get; set; } 
        public string? WearitNoneImg { get; set; } 
        public string? WearitColor { get; set; } 
        public string? WearitText { get; set; } 
        public string? ImgWearitTitle { get; set; } 
        public string? TryonCount { get; set; }
        public string? TryonStatus { get; set; } 
        public string? TryonImg { get; set; }
        public string? TryonNoneImg { get; set; } 
        public string? TryonText { get; set; } 
        public string? TryonTitle { get; set; } 
        public string? TryonAndroidPath { get; set; }
        public string? TryonIosPath { get; set; }
        public string? WishCount { get; set; }
        public string? WishDefaultImg { get; set; } 
        public string? WishFillImg { get; set; } 
        public string? ImgWishTitle { get; set; } 
        public string? ItemReview { get; set; }
        public string? ItemSize { get; set; } 
        public string? ItemKt { get; set; } 
        public string? ItemColor { get; set; } 
        public string? ItemMetal { get; set; } 
        public string? ItemWt { get; set; }
        public string? ItemStone { get; set; } 
        public string? ItemStoneWt { get; set; }
        public string? ItemStoneQty { get; set; }
        public string? StarColor { get; set; } 
        public string? ItemMetalCommonID { get; set; }
        public string? PriceText { get; set; } 
        public string? CartPrice { get; set; }
        public string? ItemColorId { get; set; }
        public string? ItemDetails { get; set; } 
        public string? ItemDiamondDetails { get; set; } 
        public string? ItemText { get; set; }
        public string? MoreItemDetails { get; set; }
        public string? ItemStock { get; set; }
        public string? CartItemQty { get; set; }
        public string? RupySymbol { get; set; }
        public string? VariantCount { get; set; }
        public string? CartId { get; set; }
        public string? ItemGenderCommonID { get; set; }
        public string? CategoryId { get; set; }
        public string? ItemNosePinScrewSts { get; set; } 
        public string? Metal { get; set; }
        public string? Kt { get; set; } 
        public string? Quality { get; set; } 
        public string? Shape { get; set; }
        public string? Brand { get; set; } 
        public string? Stone { get; set; } 
        public string? Diamondcolor { get; set; } 
        public string? Category { get; set; } 
        public string? ItemAproxDayCommonID { get; set; }
        public string? GrossWt { get; set; }
        public string? ItemFranchiseSts { get; set; } 
        public string? Priceflags { get; set; } 
        public string? ItemPlainGold { get; set; } 
        public string? ItemSoliterSts { get; set; } 
        public string? ItemSubCtgName { get; set; }
        public string? ItemSubSubCtgName { get; set; }
        public string? ItemIsSRP { get; set; }
        public string? ItemSizeAvailable { get; set; }
        public string? IsEarPiercing { get; set; }
        public string? ProductTags { get; set; } 
        public string? SubCollection { get; set; }
        public string? GemsStone { get; set; } 
        public string? DataCollection1 { get; set; } 
        public string? Next { get; set; }
        public string? Prev { get; set; }
        public string? Weight { get; set; } 
        public string? Metalweight { get; set; } 
        public string? Diamondweight { get; set; }
        public string? Approxdelivery { get; set; } 
        public string? Collections { get; set; }
        public string? ItemStockQty { get; set; }
        public string? StockColorId { get; set; }
        public string? StockSizeId { get; set; }
        public string? ItemStockColorsizeQty { get; set; }
        public string? SelectedColor { get; set; } 
        public string? SelectedSize { get; set; } 
        public string? SelectedColor1 { get; set; } 
        public string? SelectedSize1 { get; set; } 
        public string? FieldName { get; set; }
        public string? ColorName { get; set; }
        public string? DefaultColorName { get; set; }
        public string? DefaultColorCode { get; set; }
        public string? DefaultSizeName { get; set; }
        public string? Priceflag { get; set; }
        public string? FranDiamondPrice { get; set; }
        public string? DiamondWt { get; set; }
        public string? FranGoldPrice { get; set; }
        public string? GoldWt { get; set; }
        public string? GoldKtprice { get; set; }
        public string? FranPlatinumPrice { get; set; }
        public string? PlatinumWt { get; set; }
        public string? PlatinumKtprice { get; set; }
        public string? FranLabourPrice { get; set; }
        public string? FranMetalPrice { get; set; }
        public string? FranOtherPrice { get; set; }
        public string? FranStonePrice { get; set; }
        public string? StoneQty { get; set; }
        public string? StoneWt { get; set; }
        public string? FranMrpGst { get; set; }
        public object? ApproxDays { get; set; }
        public object? SizeList { get; set; }
        public object? ItemsColorSizeList { get; set; }
        public object? ItemOrderInstructionList { get; set; }
        public object? ItemOrderCustomInstructionList { get; set; }
        public object? ItemImagesColor { get; set; }
        public object? DiamondData { get; set; }
        public object? ColorList { get; set; }
        public object? ItemImages { get; set; }
        public object? FranchiseWiseStock { get; set; }
    }
}
