namespace NewAvatarWebApis.Core.Application.Responses
{
    public class ItemViewListResponse
    {
        public string? ViewId { get; set; }
        public string? ItemSoliter { get; set; }
        public string? ItemDisLabourPer { get; set; }
        public string? ItemAproxDay { get; set; }
        public string? LabourPer { get; set; }
        public string? PlainGoldStatus { get; set; }
        public string? CartId { get; set; }
        public string? DataId { get; set; }
        public string? ItemId { get; set; }
        public string? ItemCode { get; set; }
        public string? ItemName { get; set; }
        public string? ItemSku { get; set; }
        public string? ItemDescription { get; set; }
        public string? ItemMrp { get; set; }
        public string? ItemPrice { get; set; }
        public string? DistPrice { get; set; }
        public string? ImagePath { get; set; }
        public string? ImageThumbPath { get; set; }
        public string? DsgSfx { get; set; }
        public string? DsgSize { get; set; }
        public string? DsgKt { get; set; }
        public string? DsgColor { get; set; }
        public string? Star { get; set; }
        public string? CartImg { get; set; }
        public string? ImgCartTitle { get; set; }
        public string? WatchImg { get; set; }
        public string? ImgWatchTitle { get; set; }
        public string? WishCount { get; set; }
        public string? WearitCount { get; set; }
        public string? WearitStatus { get; set; }
        public string? WearitImg { get; set; }
        public string? WearitNoneImg { get; set; }
        public string? WearitColor { get; set; }
        public string? WearitText { get; set; }
        public string? ImgWearitTitle { get; set; }
        public string? WishDefaultImg { get; set; }
        public string? WishFillImg { get; set; }
        public string? ImgWishTitle { get; set; }
        public string? ItemReview { get; set; }
        public string? ItemSize { get; set; }
        public string? ItemKt { get; set; }
        public string? ItemColor { get; set; }
        public string? ItemMetal { get; set; }
        public string? ItemWt { get; set; }
        public string? ItemStone { get; set; }
        public string? ItemStoneWt { get; set; }
        public string? ItemStoneQty { get; set; }
        public string? PriceText { get; set; }
        public string? CartPrice { get; set; }
        public string? ItemColorId { get; set; }
        public string? ItemDetails { get; set; }
        public string? ItemDiamondDetails { get; set; }
        public string? ItemText { get; set; }
        public string? MoreItemDetails { get; set; }
        public string? ItemStock { get; set; }
        public string? ItemRemoveCartImg { get; set; }
        public string? ItemRemoveCartTitle { get; set; }
        public string? RupySymbol { get; set; }
        public string? RecentView { get; set; }
        public string? CategoryId { get; set; }
        public string? CartIds { get; set; }
        public string? ItemStockQty { get; set; }
        public string? ItemStockColorsizeQty { get; set; }
        public string? VariantCount { get; set; }
        public string? ItemTypeCommonID { get; set; }
        public string? ItemNosePinScrewSts { get; set; }
        public string? ItemFranchiseSts { get; set; }
        public string? ItemIllumine { get; set; }
        public string? IsSolitaireOtherCollection { get; set; }
        public string? ItemGenderCommonID { get; set; }
        public string? ProductTags { get; set; }
        public string? Weight { get; set; }
        public string? TotalLabourPer { get; set; }
        public string? FinalDMrp { get; set; }
        public string? SelectedColor { get; set; }
        public string? SelectedSize { get; set; }
        public string? SelectedColor1 { get; set; }
        public string? SelectedSize1 { get; set; }
        public string? FieldName { get; set; }
        public string? ColorName { get; set; }
        public string? DefaultColorName { get; set; }
        public object? SizeList { get; set; }
        public object? ColorList { get; set; }
        public object? ItemsColorSizeList { get; set; }
        public object? ItemOrderInstructionList { get; set; }
        public object? ItemOrderCustomInstructionList { get; set; }
        public object? ItemImagesColor { get; set; }
    }
}
